// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMX9NjpcXbF1nVmrwIGl7Z47t3vFkOe58',
    appId: '1:315297885273:web:c31ffe95bd08b390b35548',
    messagingSenderId: '315297885273',
    projectId: 'be-dining',
    authDomain: 'be-dining.firebaseapp.com',
    storageBucket: 'be-dining.appspot.com',
    measurementId: 'G-T54LHR1ZCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMMChD1hKGkQXc20CFFzB9wCFXmb-0cE',
    appId: '1:315297885273:android:8cd38c1c56ef2e90b35548',
    messagingSenderId: '315297885273',
    projectId: 'be-dining',
    storageBucket: 'be-dining.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wCC9_BhFgOXDzM0maOFwYADfRKAkkBs',
    appId: '1:315297885273:ios:65f68183d5f6d134b35548',
    messagingSenderId: '315297885273',
    projectId: 'be-dining',
    storageBucket: 'be-dining.appspot.com',
    iosBundleId: 'com.example.beDining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-wCC9_BhFgOXDzM0maOFwYADfRKAkkBs',
    appId: '1:315297885273:ios:65f68183d5f6d134b35548',
    messagingSenderId: '315297885273',
    projectId: 'be-dining',
    storageBucket: 'be-dining.appspot.com',
    iosBundleId: 'com.example.beDining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMX9NjpcXbF1nVmrwIGl7Z47t3vFkOe58',
    appId: '1:315297885273:web:8d76439884c379cfb35548',
    messagingSenderId: '315297885273',
    projectId: 'be-dining',
    authDomain: 'be-dining.firebaseapp.com',
    storageBucket: 'be-dining.appspot.com',
    measurementId: 'G-W01LNTVX26',
  );
}
